name: Makefile CI

on:
  workflow_dispatch:

env:
  SCRIPT_NAME: hello-world
  ICON_FILE: images/python.ico

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/*requirements.txt
          **/pyproject.toml
    - name: Install the project
      run: |
        uv venv  
        uv pip sync dev-requirements.txt
    - name: Build executable
      run: |
        .venv\Scripts\Activate.ps1
        python.exe mk_file_version_info.py --out "${env:SCRIPT_NAME}_info.txt" "${env:SCRIPT_NAME}.py"
        pyinstaller.exe --version-file "${env:SCRIPT_NAME}_info.txt" --onefile --icon="${env:ICON_FILE}" "${env:SCRIPT_NAME}.py"
    - name: List directory
      run: |
        dir
        dir dist
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SCRIPT_NAME }}
        path: dist/${{ env.SCRIPT_NAME }}.exe

