name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Check Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    - name: Show packages
      run: pip list
