name: Makefile CI

on:
  workflow_dispatch:

env:
  SCRIPT_NAME: hello-world

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install the project
      run: |
        uv venv  
        uv pip sync dev-requirements.txt
    - name: Create executable
      run: |
        .venv\Scripts\python.exe mk_file_version_info.py --out "${env:SCRIPT_NAME}_info.txt" "${env:SCRIPT_NAME}.py"
    - name: List directory
      run: |
        dir