name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Pyuthon version
      run: python -c "import sys; print(sys.version)"
