name: Release asset

on:
  workflow_dispatch:

env:
  SCRIPT_NAME: hello-world

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build executable
      run: |
        New-Item -Path dist -ItemType dir -Force
        Copy-Item *.py -Destination dist
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.SCRIPT_NAME}}-${{ github.ref_name }}
        path: dist

