name: Release asset

on:
  workflow_dispatch:

env:
  SCRIPT_NAME: hello-world

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.SCRIPT_NAME}}
        path: application.py

